[package]
name = "bmi-select"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
seq-macro = "0.3.6"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
fastlanes = "0.1.8"

[[bench]]
name = "bit_pack_bench"
harness = false
